# Время в минутах, после которого игрок считается AFK
afk-time-minutes: 5

# Список доступных статусов
statuses:
  stream:
    symbol: "📶 "
    color: "&d"    # Фиолетовый
  record:
    symbol: "📹 "
    color: "&c"    # Красный
  afk:
    symbol: "⌚ "
    color: "&7"    # Серый

# Настройки формата имени игрока
name-format:
  use-colors: true  # Использовать цвета вместо символов
  world-colors:
    NORMAL: "&f"   # Белый (Обычный мир)
    NETHER: "&c"   # Красный (Ад)
    THE_END: "&5"  # Фиолетовый (Энд)
  world-balls:
    NORMAL: ""      # Без символа (Обычный мир)
    NETHER: "&c●"   # Красный символ (Ад)
    THE_END: "&d●"  # Фиолетовый символ (Энд)

# Настройки чата
chat:
  enabled: true
  format: "%status%%worldprefix%%player_name%&7: &f%message%"

# Сообщения плагина
messages:
  placeholderapi_detected: "&a✔ PlaceholderAPI обнаружен. Зарегистрированы плейсхолдеры: &f%statussmp_*%"
  placeholderapi_not_found: "&c✖ PlaceholderAPI не найден. Плейсхолдеры не будут работать."
  status_disabled: "&7⏹ Статус отключен"
  status_set: "&a✔ Установлен статус: %status%"
  afk_enabled: "&7⌚ Вы теперь AFK"
  afk_disabled: "&a✔ Вы больше не AFK"
  config_reloaded: "&a✔ Конфигурация успешно перезагружена"
  no_permission: "&c✖ У вас недостаточно прав"
  player_only: "&c✖ Команда доступна только игрокам"
  usage: "&eℹ Использование: /status <%statuses%|off>"
  invalid_status: "&c✖ Неверный статус. Доступно: %statuses%, off"